import type { NextPage } from 'next'
import {useState} from 'react';
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../../components/header.component';
import Footer from '../../components/footer.component';
import styles from '../styles/Coinpage.module.css'
import utils from '../styles/Utils.module.css';

interface IProps {
    info: {
      [key: string]: any
    }[];
    prices: {
      [key: string]: any
    }
  }

const CoinPage: NextPage<IProps> = ({info, prices}) => {
    console.log(info)
    console.log(prices)
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>

      <Footer/>
    </div>
  )
}

export default CoinPage;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const data = await Promise.all([
    fetch(`https://api.coingecko.com/api/v3/coins/${context.params!.id}?localization=false`).then(res => res.json()),
    fetch(`https://api.coingecko.com/api/v3/coins/${context.params!.id}/market_chart?vs_currency=usd&days=max`).then(res => res.json())
  ])

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: {info: data[0], prices: data[1]}
  }
}